version: '3.3'
services:
    nodejs:
        image: 'node:latest'
        working_dir: /home/node/app
        command:
            - /bin/sh
            - '-c'
            - 'npm install && ./node_modules/.bin/ng serve --host 0.0.0.0'
        ports:
            - '3001:4200'
        volumes:
            - './:/home/node/app'