version: '3.3'
services:
  node:
    container_name: project_notation_ipssi
    image: 'node:latest'
    working_dir: /home/node/app
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    ports:
      - '3000:3000'
    volumes:
      - './src:/home/node/app'
    links:
      - mongo
    networks:
      - my-network
  mongo:
    container_name: project_notation_ipssi_mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network
  angular: # The name of the service
    container_name: project_notation_ipssi_angular  # Container name
    build: . # Location of our Dockerfile
    volumes: # Volume binding
      - './:/usr/src/app' 
    ports: 
      - '4200:4200' # Port mapping
    command: > 
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
networks:
  my-network:
    driver: bridge
